# Generated by Django 3.1.4 on 2021-01-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_auction', '0002_auto_20201231_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdraftingschedule',
            name='end_time',
            field=models.BigIntegerField(null=True),
        ),
    ]
