# Generated by Django 3.1.4 on 2021-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_auction', '0003_auto_20201231_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionableSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(db_index=True, max_length=3)),
                ('set_name', models.CharField(max_length=100)),
            ],
        ),
    ]
